 <div class="row">
     <div class="col-md-8">
         <form name="addData" method="post" id="addData" class="form" action="<?php echo $this->getFormAction(); ?>" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
             <div class="row">
                 <div class="col-md-8">
                     <form name="addData" method="post" id="addData" class="form" action="<?php echo $this->getFormAction(); ?>" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
                         <fieldset class="fieldset">
                             <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                             <fieldset class="fieldset row">
                                 <div class="fields col-md-6">
                                     <div class="field name required">
                                         <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Name')) ?></span></label>
                                         <div class="control">
                                             <input name="name" id="name" title="Name" value="" class="input-text" type="text" data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                                         </div>
                                     </div>
                                     <div class="field name required">
                                         <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Email')) ?></span></label>
                                         <div class="control">
                                             <input name="email" id="email" title="Email" value="" class="input-text" type="text" data-validate="{required:true, 'validate-email':true}">
                                         </div>
                                     </div>
                                     <div class="field name required">
                                         <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Mobile')) ?></span></label>
                                         <div class="control">
                                             <input name="mobile" id="mobile" title="Mobile" value="" class="input-text" type="text" data-validate="{required:true,'validate-number':true}">
                                         </div>
                                     </div>
                                     <div class="field name required">
                                         <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Comments')) ?></span></label>
                                         <div class="control">
                                             <textarea name="comments" id="comments" title="Comments" value="" class="input-text" type="text" data-validate="{required:true}"></textarea>
                                         </div>
                                     </div>
                                 </div>
                             </fieldset>
                         </fieldset>
                         <div class="actions-toolbar">
                             <div class="primary">
                                 <button type="submit" class="action submit primary" title="Save"><span><?= $block->escapeHtmlAttr(__('Save')) ?></span></button>
                             </div>
                             <div class="primary">
                                 <a href="<?php echo $this->viewformdataAction(); ?>"> <button type="button" class="action submit primary" title="show"><span><?= $block->escapeHtmlAttr(__('Show All')) ?></span></button></a>
                             </div>
                         </div>
                     </form>
                 </div>