<?php
$collection = $block->getCollection();
if ($collection->count()) {
?>
    <div class="table-wrapper orders-history">
        <div class="row">
            <div class="col-md-12" style="float: right;">
                <a href="<?= $block->getUrl('grid/index/index') ?>" class="action primary">Add New</a>
            </div>
        </div>
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php echo __('ID') ?></th>
                    <th scope="col" class="col name"><?php echo __('Name') ?></th>
                    <th scope="col" class="col email"><?php echo __('Email') ?></th>
                    <th scope="col" class="col mobile"><?php echo __('Mobile') ?></th>
                    <th scope="col" class="col comments"><?php echo __('Comments') ?></th>
                    <th scope="col" class="col createat"><?php echo __('Created At') ?></th>
                    <th colspan="2" style="padding-left:10px;"><?= __('Action'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($collection as $item) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                            <?php echo $item->getId() ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col name">
                            <?php echo $item->getName() ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col email">
                            <?php echo $item->getEmail() ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Mobile')) ?>" class="col mobile">
                            <?php echo $item->getMobile() ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Comments')) ?>" class="col comments">
                            <?php echo $item->getComments() ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Created At')) ?>" class="col title"><?php echo date('Y-m-d', strtotime($item->getCreatedAt())); ?></td>
                        <td>
                            <a href="<?php echo $block->getEditAction() . 'id/' . $item->getId(); ?>" class="action primary">Edit</a>
                        </td>
                        <td>
                            <a href="<?php echo $block->getDeleteAction() . 'id/' . $item->getId(); ?>" class="action primary">Delete</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php
}
?>