<h2>CUSTOM OPEN SOURCE CHECKOUT FOR BIGCOMMERCE</h2>
<p>Earlier in BigCommerce, the only way to edit the optimized one-page checkout provided by BigCommerce was to implement checkout SDK, which does not replicate all the features of BigCommerce checkout. With this recent release of open-source checkout, we can edit the exact optimized one-page checkout of BigCommerce.

    This blog will let you know how to edit the Checkout page in <a href="https://www.dckap.com/blog/custom-open-source-checkout-for-bigcommerce/">BigCommerce</a>.</p>